name: RPGAttackSystem
version: '1.1'
main: me.xuanlam2007.RPGAttackSystem
api-version: '1.21'
author: XuanLam
website: https://github.com/xuanlam2007
commands:
  rpgattacksystem:
    description: Main plugin command
    usage: /<command> <reload|info>
    aliases: [ras]
permissions:
  rpgattacksystem.reload:
    description: Reload plugin config
    default: op
  rpgattacksystem.info:
    description: Show plugin info
    default: op